[tools]
hadolint = "2.12.0"
shellcheck = "0.10"
terragrunt = "0"

[tasks.pre-commit]
description = "Run pre-commit"
run = "pre-commit run --all-files --color always"

[tasks.fmt]
description = "Format HCL files"
run = "terragrunt hcl fmt"
